#!/usr/bin/env python3
"""
Némesis IA - Document Templates
Capítulo 10: El Fiscal Digital

Templates para documentos legales
"""

from datetime import datetime
from typing import Dict, List


class DocumentTemplates:
    """Templates para documentos legales"""
    
    @staticmethod
    def incident_report_template(incident_data: Dict) -> Dict:
        """
        Template para reporte de incidente
        
        Args:
            incident_data: Datos del incidente
            
        Returns:
            Diccionario con estructura del documento
        """
        
        return {
            'title': 'CYBERSECURITY INCIDENT REPORT',
            'subtitle': f"Case #{incident_data.get('case_id', 'UNKNOWN')}",
            'metadata': {
                'Report Date': datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC'),
                'Case ID': incident_data.get('case_id', 'N/A'),
                'Severity': incident_data.get('severity', 'N/A'),
                'Status': incident_data.get('status', 'OPEN'),
                'Generated By': 'NEMESIS IA Forensic System'
            },
            'sections': [
                {
                    'title': '1. EXECUTIVE SUMMARY',
                    'content': incident_data.get(
                        'executive_summary',
                        'A cybersecurity incident was detected and documented by the NEMESIS IA '
                        'autonomous defense system. This report contains forensic evidence, '
                        'technical analysis, and recommended actions.'
                    )
                },
                {
                    'title': '2. INCIDENT DETAILS',
                    'content': f"""
                    <b>Incident Type:</b> {incident_data.get('incident_type', 'N/A')}<br/>
                    <b>Detection Time:</b> {incident_data.get('detection_time', 'N/A')}<br/>
                    <b>Source IP:</b> {incident_data.get('source_ip', 'N/A')}<br/>
                    <b>Target:</b> {incident_data.get('target', 'N/A')}<br/>
                    <b>Confidence Level:</b> {incident_data.get('confidence', 0.0)*100:.1f}%<br/>
                    <b>Attack Vector:</b> {incident_data.get('attack_vector', 'N/A')}<br/>
                    """
                },
                {
                    'title': '3. TECHNICAL ANALYSIS',
                    'content': incident_data.get(
                        'technical_analysis',
                        'Detailed technical analysis of the attack patterns, methods, and potential impact. '
                        'This section includes network traffic analysis, payload examination, and behavioral indicators.'
                    )
                },
                {
                    'title': '4. EVIDENCE COLLECTED',
                    'content': f"""
                    Evidence has been collected and stored using blockchain technology to maintain 
                    chain of custody integrity. All evidence items are cryptographically verified 
                    and admissible in court proceedings.<br/><br/>
                    <b>Evidence Items:</b> {incident_data.get('evidence_count', 0)}<br/>
                    <b>Blockchain Hash:</b> {incident_data.get('blockchain_hash', 'N/A')[:32]}...<br/>
                    """
                },
                {
                    'title': '5. IMPACT ASSESSMENT',
                    'content': incident_data.get(
                        'impact_assessment',
                        'Assessment of actual and potential impact on systems, data, and operations. '
                        'Includes evaluation of compromised assets and business continuity implications.'
                    )
                },
                {
                    'title': '6. RESPONSE ACTIONS TAKEN',
                    'content': incident_data.get(
                        'response_actions',
                        'Automated response actions were executed by NEMESIS IA system including: '
                        'IP blocking, traffic filtering, alert generation, and evidence preservation.'
                    )
                },
                {
                    'title': '7. RECOMMENDATIONS',
                    'content': incident_data.get(
                        'recommendations',
                        'Recommended actions to prevent similar incidents: Update firewall rules, '
                        'patch vulnerable systems, enhance monitoring, conduct security awareness training.'
                    )
                }
            ],
            'signatures': [
                {
                    'name': 'NEMESIS IA System',
                    'title': 'Autonomous Cybersecurity Defense',
                    'date': datetime.now().strftime('%Y-%m-%d')
                },
                {
                    'name': 'Security Operations Center',
                    'title': 'SOC Analyst',
                    'date': ''
                }
            ]
        }
    
    @staticmethod
    def evidence_report_template(evidence_data: Dict) -> Dict:
        """Template para reporte de evidencia"""
        
        return {
            'title': 'FORENSIC EVIDENCE REPORT',
            'subtitle': f"Evidence ID: {evidence_data.get('evidence_id', 'UNKNOWN')}",
            'metadata': {
                'Report Date': datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC'),
                'Evidence ID': evidence_data.get('evidence_id', 'N/A'),
                'Classification': evidence_data.get('classification', 'CONFIDENTIAL'),
                'Chain of Custody': 'VERIFIED',
                'Generated By': 'NEMESIS IA Forensic System'
            },
            'sections': [
                {
                    'title': '1. EVIDENCE IDENTIFICATION',
                    'content': f"""
                    This report documents forensic evidence collected during a cybersecurity incident 
                    investigation. The evidence has been preserved using blockchain technology to ensure 
                    integrity and admissibility.<br/><br/>
                    <b>Evidence Type:</b> {evidence_data.get('evidence_type', 'N/A')}<br/>
                    <b>Collection Method:</b> {evidence_data.get('collection_method', 'Automated')}<br/>
                    <b>Collected By:</b> {evidence_data.get('collected_by', 'NEMESIS_IA')}<br/>
                    <b>Collection Time:</b> {evidence_data.get('collection_time', 'N/A')}<br/>
                    """
                },
                {
                    'title': '2. CRYPTOGRAPHIC VERIFICATION',
                    'content': f"""
                    <b>SHA-256 Hash:</b> {evidence_data.get('hash', 'N/A')}<br/>
                    <b>Blockchain Block:</b> {evidence_data.get('block_index', 'N/A')}<br/>
                    <b>Previous Block Hash:</b> {evidence_data.get('previous_hash', 'N/A')[:32]}...<br/>
                    <b>Verification Status:</b> ✓ VERIFIED<br/><br/>
                    The cryptographic hash ensures that any tampering with this evidence will be 
                    immediately detectable. This evidence maintains full chain of custody integrity 
                    and is admissible in court proceedings.
                    """
                },
                {
                    'title': '3. CHAIN OF CUSTODY',
                    'content': f"""
                    Complete chain of custody has been maintained from collection through analysis. 
                    All transfers and access events are cryptographically recorded.<br/><br/>
                    <b>Custody Events:</b> {evidence_data.get('custody_events', 0)}<br/>
                    <b>Current Handler:</b> {evidence_data.get('current_handler', 'N/A')}<br/>
                    <b>Location:</b> {evidence_data.get('location', 'EVIDENCE_STORAGE')}<br/>
                    """
                },
                {
                    'title': '4. TECHNICAL DETAILS',
                    'content': evidence_data.get(
                        'technical_details',
                        'Detailed technical analysis of the evidence including metadata, content analysis, '
                        'and relevant indicators of compromise.'
                    )
                },
                {
                    'title': '5. LEGAL COMPLIANCE',
                    'content': """
                    This evidence has been collected and preserved in compliance with:<br/>
                    • ISO/IEC 27037:2012 - Guidelines for identification, collection, acquisition and preservation of digital evidence<br/>
                    • Federal Rules of Evidence (FRE)<br/>
                    • Electronic Discovery Reference Model (EDRM)<br/>
                    • Chain of custody best practices<br/><br/>
                    All procedures ensure admissibility in legal proceedings.
                    """
                }
            ]
        }
    
    @staticmethod
    def legal_complaint_template(complaint_data: Dict) -> Dict:
        """Template para denuncia legal"""
        
        return {
            'title': 'LEGAL COMPLAINT',
            'subtitle': 'Cybersecurity Incident Report for Law Enforcement',
            'metadata': {
                'Complaint Date': datetime.now().strftime('%Y-%m-%d'),
                'Case Reference': complaint_data.get('case_id', 'N/A'),
                'Reporting Entity': complaint_data.get('entity', 'Organization'),
                'Incident Date': complaint_data.get('incident_date', 'N/A')
            },
            'sections': [
                {
                    'title': 'COMPLAINT SUMMARY',
                    'content': complaint_data.get(
                        'summary',
                        'This complaint documents a cybersecurity incident involving unauthorized access, '
                        'malicious activity, or attempted compromise of computer systems. Evidence has been '
                        'preserved and is available for law enforcement investigation.'
                    )
                },
                {
                    'title': 'INCIDENT DESCRIPTION',
                    'content': f"""
                    <b>Type of Incident:</b> {complaint_data.get('incident_type', 'N/A')}<br/>
                    <b>Date and Time:</b> {complaint_data.get('incident_datetime', 'N/A')}<br/>
                    <b>Source of Attack:</b> {complaint_data.get('source_ip', 'Unknown')}<br/>
                    <b>Targeted Systems:</b> {complaint_data.get('target_systems', 'N/A')}<br/>
                    <b>Estimated Damage:</b> {complaint_data.get('damage_estimate', 'Under investigation')}<br/>
                    """
                },
                {
                    'title': 'EVIDENCE AVAILABLE',
                    'content': f"""
                    Forensic evidence has been preserved using cryptographic blockchain technology:<br/><br/>
                    <b>Evidence Items:</b> {complaint_data.get('evidence_count', 0)}<br/>
                    <b>Evidence IDs:</b> {', '.join(complaint_data.get('evidence_ids', []))}<br/>
                    <b>Chain of Custody:</b> Maintained and Verified<br/>
                    <b>Format:</b> Digital forensic evidence package<br/>
                    """
                },
                {
                    'title': 'APPLICABLE LAWS',
                    'content': """
                    This incident may constitute violations of:<br/>
                    • Computer Fraud and Abuse Act (CFAA) - 18 U.S.C. § 1030<br/>
                    • Electronic Communications Privacy Act (ECPA)<br/>
                    • State computer crime statutes<br/>
                    • Relevant international cybercrime treaties<br/>
                    """
                },
                {
                    'title': 'REQUESTED ACTION',
                    'content': complaint_data.get(
                        'requested_action',
                        'We request investigation of this incident and prosecution of responsible parties '
                        'to the fullest extent of the law. All evidence is preserved and available for '
                        'law enforcement examination.'
                    )
                }
            ],
            'signatures': [
                {
                    'name': complaint_data.get('complainant_name', 'Authorized Representative'),
                    'title': complaint_data.get('complainant_title', 'Chief Security Officer'),
                    'date': datetime.now().strftime('%Y-%m-%d')
                }
            ]
        }