#!/usr/bin/env python3
"""
Némesis IA - Fiscal Digital
Capítulo 10: El Fiscal Digital

Sistema completo de generación de documentos legales
"""

import logging
import os
from datetime import datetime
from typing import Dict, List, Optional
from reportlab.platypus import PageBreak, Spacer

from .pdf_generator import PDFGenerator
from .document_templates import DocumentTemplates

logger = logging.getLogger(__name__)


class FiscalDigital:
    """Sistema de generación automática de documentos legales"""
    
    def __init__(self, output_dir: str = "legal_documents"):
        """
        Inicializa Fiscal Digital
        
        Args:
            output_dir: Directorio para documentos generados
        """
        
        self.pdf_generator = PDFGenerator()
        self.templates = DocumentTemplates()
        self.output_dir = output_dir
        
        # Crear directorio si no existe
        os.makedirs(output_dir, exist_ok=True)
        
        # Estadísticas
        self.stats = {
            "incident_reports": 0,
            "evidence_reports": 0,
            "legal_complaints": 0,
            "custody_reports": 0,
            "total_documents": 0
        }
        
        logger.info(f"⚖️ FiscalDigital inicializado - Output: {output_dir}")
    
    def generate_incident_report(
        self,
        incident_data: Dict,
        filename: Optional[str] = None
    ) -> str:
        """
        Genera reporte completo de incidente
        
        Args:
            incident_data: Datos del incidente
            filename: Nombre del archivo (opcional)
            
        Returns:
            Ruta del archivo generado
        """
        
        logger.info("📋 Generando reporte de incidente...")
        
        # Obtener template
        template = self.templates.incident_report_template(incident_data)
        
        # Generar nombre de archivo
        if not filename:
            case_id = incident_data.get('case_id', 'UNKNOWN')
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"INCIDENT_REPORT_{case_id}_{timestamp}.pdf"
        
        filepath = os.path.join(self.output_dir, filename)
        
        # Construir elementos del PDF
        elements = []
        
        # Header
        elements.extend(self.pdf_generator.add_header(
            title=template['title'],
            subtitle=template['subtitle'],
            metadata=template['metadata']
        ))
        
        # Disclaimer legal
        disclaimer = self.pdf_generator.generate_legal_disclaimer()
        elements.extend(self.pdf_generator.add_section(
            title="LEGAL NOTICE",
            content=disclaimer,
            style='Metadata'
        ))
        
        elements.append(PageBreak())
        
        # Secciones
        for section in template['sections']:
            elements.extend(self.pdf_generator.add_section(
                title=section['title'],
                content=section['content']
            ))
        
        # Caja de evidencia si hay datos
        if incident_data.get('evidence_id'):
            evidence_box_data = {
                'evidence_id': incident_data.get('evidence_id'),
                'type': incident_data.get('incident_type'),
                'collected_at': incident_data.get('detection_time'),
                'hash': incident_data.get('evidence_hash', 'N/A'),
                'classification': incident_data.get('classification', 'CONFIDENTIAL')
            }
            elements.extend(self.pdf_generator.add_evidence_box(evidence_box_data))
        
        # Firmas
        if template.get('signatures'):
            elements.extend(self.pdf_generator.add_signature_section(
                template['signatures']
            ))
        
        # Footer
        footer_text = f"Generated by NEMESIS IA Forensic System | {datetime.now().isoformat()} | Page "
        elements.extend(self.pdf_generator.add_footer_text(footer_text))
        
        # Generar PDF
        self.pdf_generator.build_pdf(filepath, elements, template['title'])
        
        self.stats['incident_reports'] += 1
        self.stats['total_documents'] += 1
        
        logger.info(f"✅ Reporte generado: {filepath}")
        
        return filepath
    
    def generate_evidence_report(
        self,
        evidence_data: Dict,
        filename: Optional[str] = None
    ) -> str:
        """
        Genera reporte de evidencia forense
        
        Args:
            evidence_data: Datos de la evidencia
            filename: Nombre del archivo (opcional)
            
        Returns:
            Ruta del archivo generado
        """
        
        logger.info("🔬 Generando reporte de evidencia...")
        
        # Obtener template
        template = self.templates.evidence_report_template(evidence_data)
        
        # Generar nombre de archivo
        if not filename:
            evidence_id = evidence_data.get('evidence_id', 'UNKNOWN')
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"EVIDENCE_REPORT_{evidence_id}_{timestamp}.pdf"
        
        filepath = os.path.join(self.output_dir, filename)
        
        # Construir elementos
        elements = []
        
        # Header
        elements.extend(self.pdf_generator.add_header(
            title=template['title'],
            subtitle=template['subtitle'],
            metadata=template['metadata']
        ))
        
        # Caja de evidencia destacada
        elements.extend(self.pdf_generator.add_evidence_box(evidence_data))
        
        # Secciones
        for section in template['sections']:
            elements.extend(self.pdf_generator.add_section(
                title=section['title'],
                content=section['content']
            ))
        
        # Tabla de chain of custody si disponible
        if evidence_data.get('custody_events'):
            elements.append(Spacer(1, 20))
            
            custody_data = [
                ['Event', 'Handler', 'Time', 'Action']
            ]
            
            for event in evidence_data.get('custody_events', [])[:5]:  # Top 5
                custody_data.append([
                    str(event.get('index', '')),
                    event.get('handler', 'N/A'),
                    event.get('timestamp', 'N/A'),
                    event.get('action', 'N/A')
                ])
            
            table = self.pdf_generator.add_table(custody_data)
            elements.append(table)
            elements.append(Spacer(1, 20))
        
        # Disclaimer
        disclaimer = """
        This forensic evidence report has been generated using cryptographic blockchain 
        technology to ensure integrity. Any modification to the evidence will be detectable 
        through hash verification. This report is admissible in court proceedings.
        """
        elements.extend(self.pdf_generator.add_section(
            title="ADMISSIBILITY STATEMENT",
            content=disclaimer
        ))
        
        # Generar PDF
        self.pdf_generator.build_pdf(filepath, elements, template['title'])
        
        self.stats['evidence_reports'] += 1
        self.stats['total_documents'] += 1
        
        logger.info(f"✅ Reporte de evidencia generado: {filepath}")
        
        return filepath
    
    def generate_legal_complaint(
        self,
        complaint_data: Dict,
        filename: Optional[str] = None
    ) -> str:
        """
        Genera denuncia legal
        
        Args:
            complaint_data: Datos de la denuncia
            filename: Nombre del archivo (opcional)
            
        Returns:
            Ruta del archivo generado
        """
        
        logger.info("⚖️ Generando denuncia legal...")
        
        # Obtener template
        template = self.templates.legal_complaint_template(complaint_data)
        
        # Generar nombre de archivo
        if not filename:
            case_id = complaint_data.get('case_id', 'UNKNOWN')
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"LEGAL_COMPLAINT_{case_id}_{timestamp}.pdf"
        
        filepath = os.path.join(self.output_dir, filename)
        
        # Construir elementos
        elements = []
        
        # Header
        elements.extend(self.pdf_generator.add_header(
            title=template['title'],
            subtitle=template['subtitle'],
            metadata=template['metadata']
        ))
        
        # Secciones
        for section in template['sections']:
            elements.extend(self.pdf_generator.add_section(
                title=section['title'],
                content=section['content']
            ))
        
        # Tabla de evidencia
        if complaint_data.get('evidence_ids'):
            elements.append(Spacer(1, 20))
            
            evidence_table_data = [
                ['Evidence ID', 'Type', 'Status']
            ]
            
            for eid in complaint_data.get('evidence_ids', []):
                evidence_table_data.append([
                    eid,
                    complaint_data.get('incident_type', 'CYBER_ATTACK'),
                    '✓ PRESERVED'
                ])
            
            table = self.pdf_generator.add_table(evidence_table_data)
            elements.append(table)
            elements.append(Spacer(1, 20))
        
        # Firmas
        if template.get('signatures'):
            elements.extend(self.pdf_generator.add_signature_section(
                template['signatures']
            ))
        
        # Footer legal
        footer = """
        This complaint is filed in good faith and contains accurate information to the best 
        of our knowledge. Supporting evidence is available for law enforcement examination.
        """
        elements.extend(self.pdf_generator.add_footer_text(footer))
        
        # Generar PDF
        self.pdf_generator.build_pdf(filepath, elements, template['title'])
        
        self.stats['legal_complaints'] += 1
        self.stats['total_documents'] += 1
        
        logger.info(f"✅ Denuncia legal generada: {filepath}")
        
        return filepath
    
    def generate_chain_of_custody_report(
        self,
        custody_data: Dict,
        filename: Optional[str] = None
    ) -> str:
        """
        Genera reporte de cadena de custodia standalone
        
        Args:
            custody_data: Datos de custodia
            filename: Nombre del archivo
            
        Returns:
            Ruta del archivo
        """
        
        logger.info("🔗 Generando reporte de chain of custody...")
        
        # Generar nombre de archivo
        if not filename:
            evidence_id = custody_data.get('evidence_id', 'UNKNOWN')
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f"CUSTODY_REPORT_{evidence_id}_{timestamp}.pdf"
        
        filepath = os.path.join(self.output_dir, filename)
        
        # Construir elementos
        elements = []
        
        # Header
        elements.extend(self.pdf_generator.add_header(
            title="CHAIN OF CUSTODY REPORT",
            subtitle=f"Evidence ID: {custody_data.get('evidence_id', 'UNKNOWN')}",
            metadata={
                'Report Date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'Evidence ID': custody_data.get('evidence_id', 'N/A'),
                'Total Events': len(custody_data.get('events', [])),
                'Integrity': 'VERIFIED' if custody_data.get('valid', True) else 'COMPROMISED'
            }
        ))
        
        # Introducción
        intro = """
        This document provides a complete chain of custody record for forensic evidence. 
        All custody transfers and access events are documented with cryptographic verification. 
        This chain of custody is maintained using blockchain technology to ensure integrity 
        and admissibility in legal proceedings.
        """
        elements.extend(self.pdf_generator.add_section(
            title="INTRODUCTION",
            content=intro
        ))
        
        # Tabla de eventos de custodia
        elements.append(Spacer(1, 20))
        
        custody_table_data = [
            ['#', 'Date/Time', 'Action', 'Handler', 'Hash']
        ]
        
        for i, event in enumerate(custody_data.get('events', []), 1):
            custody_table_data.append([
                str(i),
                event.get('timestamp', 'N/A')[:19],
                event.get('action', 'N/A'),
                event.get('handler', 'N/A'),
                event.get('hash_after', 'N/A')[:16] + '...'
            ])
        
        table = self.pdf_generator.add_table(
            custody_table_data,
            column_widths=[0.5*72, 1.5*72, 1.2*72, 1.5*72, 1.8*72]
        )
        elements.append(table)
        elements.append(Spacer(1, 20))
        
        # Verificación de integridad
        integrity_text = f"""
        <b>Integrity Verification:</b> {'✓ PASSED' if custody_data.get('valid', True) else '✗ FAILED'}<br/>
        <b>Hash Algorithm:</b> SHA-256<br/>
        <b>Blockchain Verified:</b> {'✓ YES' if custody_data.get('blockchain_valid', True) else '✗ NO'}<br/>
        <b>Total Custody Events:</b> {len(custody_data.get('events', []))}<br/>
        <b>Current Handler:</b> {custody_data.get('current_handler', 'N/A')}<br/>
        """
        
        elements.extend(self.pdf_generator.add_section(
            title="INTEGRITY VERIFICATION",
            content=integrity_text
        ))
        
        # Compliance statement
        compliance = """
        This chain of custody report complies with ISO/IEC 27037:2012 guidelines for 
        identification, collection, acquisition and preservation of digital evidence. 
        All procedures ensure admissibility in court proceedings.
        """
        elements.extend(self.pdf_generator.add_section(
            title="COMPLIANCE STATEMENT",
            content=compliance
        ))
        
        # Generar PDF
        self.pdf_generator.build_pdf(filepath, elements, "Chain of Custody Report")
        
        self.stats['custody_reports'] += 1
        self.stats['total_documents'] += 1
        
        logger.info(f"✅ Reporte de custody generado: {filepath}")
        
        return filepath
    
    def generate_complete_legal_package(
        self,
        incident_data: Dict,
        evidence_data: Dict,
        custody_data: Dict,
        package_name: Optional[str] = None
    ) -> Dict[str, str]:
        """
        Genera paquete legal completo
        
        Args:
            incident_data: Datos del incidente
            evidence_data: Datos de evidencia
            custody_data: Datos de custodia
            package_name: Nombre del paquete
            
        Returns:
            Diccionario con rutas de todos los documentos
        """
        
        logger.info("📦 Generando paquete legal completo...")
        
        if not package_name:
            case_id = incident_data.get('case_id', 'UNKNOWN')
            package_name = f"LEGAL_PACKAGE_{case_id}"
        
        # Crear subdirectorio para el paquete
        package_dir = os.path.join(self.output_dir, package_name)
        os.makedirs(package_dir, exist_ok=True)
        
        # Guardar directorio original
        original_dir = self.output_dir
        self.output_dir = package_dir
        
        # Generar todos los documentos
        documents = {}
        
        try:
            # 1. Reporte de incidente
            documents['incident_report'] = self.generate_incident_report(
                incident_data,
                filename="01_INCIDENT_REPORT.pdf"
            )
            
            # 2. Reporte de evidencia
            documents['evidence_report'] = self.generate_evidence_report(
                evidence_data,
                filename="02_EVIDENCE_REPORT.pdf"
            )
            
            # 3. Chain of custody
            documents['custody_report'] = self.generate_chain_of_custody_report(
                custody_data,
                filename="03_CHAIN_OF_CUSTODY.pdf"
            )
            
            # 4. Denuncia legal
            complaint_data = {
                **incident_data,
                'evidence_ids': [evidence_data.get('evidence_id')],
                'evidence_count': 1
            }
            documents['legal_complaint'] = self.generate_legal_complaint(
                complaint_data,
                filename="04_LEGAL_COMPLAINT.pdf"
            )
            
            logger.info(f"✅ Paquete legal completo generado: {package_dir}")
            
        finally:
            # Restaurar directorio original
            self.output_dir = original_dir
        
        return documents
    
    def get_statistics(self) -> Dict:
        """Obtiene estadísticas de generación"""
        return self.stats.copy()
    
    def generate_summary_report(self) -> str:
        """Genera reporte resumen de actividad"""
        
        stats = self.get_statistics()
        
        summary = f"""
╔══════════════════════════════════════════════════════════════════╗
║              FISCAL DIGITAL - ACTIVITY SUMMARY                   ║
╚══════════════════════════════════════════════════════════════════╝

📊 Document Generation Statistics:

   Incident Reports:      {stats['incident_reports']}
   Evidence Reports:      {stats['evidence_reports']}
   Legal Complaints:      {stats['legal_complaints']}
   Custody Reports:       {stats['custody_reports']}
   
   Total Documents:       {stats['total_documents']}

📁 Output Directory:      {self.output_dir}

⚖️ All documents are legally compliant and court-admissible.

═══════════════════════════════════════════════════════════════════
"""
        
        return summary